//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 02:12:02 PM EDT 
//


package org.example.kickappnotice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.kickappnotice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NoticeInfo_QNAME = new QName("http://www.example.org/KickappNotice", "NoticeInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.kickappnotice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NoticeInfoType }
     * 
     */
    public NoticeInfoType createNoticeInfoType() {
        return new NoticeInfoType();
    }

    /**
     * Create an instance of {@link EntryType2 }
     * 
     */
    public EntryType2 createEntryType2() {
        return new EntryType2();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoticeInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/KickappNotice", name = "NoticeInfo")
    public JAXBElement<NoticeInfoType> createNoticeInfo(NoticeInfoType value) {
        return new JAXBElement<NoticeInfoType>(_NoticeInfo_QNAME, NoticeInfoType.class, null, value);
    }

}
