//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 02:12:02 PM EDT 
//


package com.kick.test.webservices.accountservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.kick.test.webservices.Account4KickInput;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="setPromotionValues" type="{http://webservices.test.kick.com}Account4kickInput"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "setPromotionValues"
})
@XmlRootElement(name = "Account4kickRequest")
public class Account4KickRequest {

    @XmlElement(required = true)
    protected Account4KickInput setPromotionValues;

    /**
     * Gets the value of the setPromotionValues property.
     * 
     * @return
     *     possible object is
     *     {@link Account4KickInput }
     *     
     */
    public Account4KickInput getSetPromotionValues() {
        return setPromotionValues;
    }

    /**
     * Sets the value of the setPromotionValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account4KickInput }
     *     
     */
    public void setSetPromotionValues(Account4KickInput value) {
        this.setPromotionValues = value;
    }

}
