//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 04:42:24 PM EDT 
//


package com.kick.test.webservices.accountservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kick.test.webservices.accountservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kick.test.webservices.accountservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Account4KickRequest }
     * 
     */
    public Account4KickRequest createAccount4KickRequest() {
        return new Account4KickRequest();
    }

    /**
     * Create an instance of {@link Account4KickResponse }
     * 
     */
    public Account4KickResponse createAccount4KickResponse() {
        return new Account4KickResponse();
    }

    /**
     * Create an instance of {@link AccountDetailsRequest }
     * 
     */
    public AccountDetailsRequest createAccountDetailsRequest() {
        return new AccountDetailsRequest();
    }

    /**
     * Create an instance of {@link AccountDetailsResponse }
     * 
     */
    public AccountDetailsResponse createAccountDetailsResponse() {
        return new AccountDetailsResponse();
    }

}
