//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 02:12:02 PM EDT 
//


package org.example.kickappnotice.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.example.kickappnotice.NoticeInfoType;


/**
 * <p>Java class for NotificationRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificationRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Notificationinfo" type="{http://www.example.org/KickappNotice}NoticeInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationRequestType", propOrder = {
    "notificationinfo"
})
public class NotificationRequestType {

    @XmlElement(name = "Notificationinfo", required = true)
    protected NoticeInfoType notificationinfo;

    /**
     * Gets the value of the notificationinfo property.
     * 
     * @return
     *     possible object is
     *     {@link NoticeInfoType }
     *     
     */
    public NoticeInfoType getNotificationinfo() {
        return notificationinfo;
    }

    /**
     * Sets the value of the notificationinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoticeInfoType }
     *     
     */
    public void setNotificationinfo(NoticeInfoType value) {
        this.notificationinfo = value;
    }

}
