//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 04:42:24 PM EDT 
//


package org.example.kickappnotice.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.kickappnotice.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NoticeRequest_QNAME = new QName("http://www.example.org/KickappNotice/service", "NoticeRequest");
    private final static QName _NoticeResponse_QNAME = new QName("http://www.example.org/KickappNotice/service", "NoticeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.kickappnotice.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotificationRequestType }
     * 
     */
    public NotificationRequestType createNotificationRequestType() {
        return new NotificationRequestType();
    }

    /**
     * Create an instance of {@link NotificationStatus }
     * 
     */
    public NotificationStatus createNotificationStatus() {
        return new NotificationStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/KickappNotice/service", name = "NoticeRequest")
    public JAXBElement<NotificationRequestType> createNoticeRequest(NotificationRequestType value) {
        return new JAXBElement<NotificationRequestType>(_NoticeRequest_QNAME, NotificationRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/KickappNotice/service", name = "NoticeResponse")
    public JAXBElement<NotificationStatus> createNoticeResponse(NotificationStatus value) {
        return new JAXBElement<NotificationStatus>(_NoticeResponse_QNAME, NotificationStatus.class, null, value);
    }

}
