//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 03:29:01 PM EDT 
//


package org.example.testkickapp1schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.testkickapp1schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NoticeElement_QNAME = new QName("http://www.example.org/TestKickapp1Schema", "NoticeElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.testkickapp1schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link NoticeType }
     * 
     */
    public NoticeType createNoticeType() {
        return new NoticeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoticeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/TestKickapp1Schema", name = "NoticeElement")
    public JAXBElement<NoticeType> createNoticeElement(NoticeType value) {
        return new JAXBElement<NoticeType>(_NoticeElement_QNAME, NoticeType.class, null, value);
    }

}
