//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 04:42:24 PM EDT 
//


package com.kick.test.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Account4kickInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Account4kickInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cnn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Preference" type="{http://webservices.test.kick.com}PrefType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Account4kickInput", propOrder = {
    "cnn",
    "name",
    "status",
    "preference"
})
public class Account4KickInput {

    @XmlElement(name = "Cnn", required = true)
    protected String cnn;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Status")
    protected double status;
    @XmlElement(name = "Preference", required = true)
    protected PrefType preference;

    /**
     * Gets the value of the cnn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnn() {
        return cnn;
    }

    /**
     * Sets the value of the cnn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnn(String value) {
        this.cnn = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public double getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(double value) {
        this.status = value;
    }

    /**
     * Gets the value of the preference property.
     * 
     * @return
     *     possible object is
     *     {@link PrefType }
     *     
     */
    public PrefType getPreference() {
        return preference;
    }

    /**
     * Sets the value of the preference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefType }
     *     
     */
    public void setPreference(PrefType value) {
        this.preference = value;
    }

}
