//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 02:12:02 PM EDT 
//


package com.kick.test.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Account4kickInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Account4kickInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ccn" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="prmotionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="securityToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="preference" type="{http://webservices.test.kick.com}PrefType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Account4kickInput", propOrder = {
    "ccn",
    "prmotionName",
    "securityToken",
    "preference"
})
public class Account4KickInput {

    protected long ccn;
    @XmlElement(required = true)
    protected String prmotionName;
    @XmlElement(required = true)
    protected String securityToken;
    @XmlElement(required = true)
    protected PrefType preference;

    /**
     * Gets the value of the ccn property.
     * 
     */
    public long getCcn() {
        return ccn;
    }

    /**
     * Sets the value of the ccn property.
     * 
     */
    public void setCcn(long value) {
        this.ccn = value;
    }

    /**
     * Gets the value of the prmotionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrmotionName() {
        return prmotionName;
    }

    /**
     * Sets the value of the prmotionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrmotionName(String value) {
        this.prmotionName = value;
    }

    /**
     * Gets the value of the securityToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityToken() {
        return securityToken;
    }

    /**
     * Sets the value of the securityToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityToken(String value) {
        this.securityToken = value;
    }

    /**
     * Gets the value of the preference property.
     * 
     * @return
     *     possible object is
     *     {@link PrefType }
     *     
     */
    public PrefType getPreference() {
        return preference;
    }

    /**
     * Sets the value of the preference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefType }
     *     
     */
    public void setPreference(PrefType value) {
        this.preference = value;
    }

}
