//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 04:42:24 PM EDT 
//


package com.kick.test.webservices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kick.test.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Account_QNAME = new QName("http://webservices.test.kick.com", "Account");
    private final static QName _Account4KickInput_QNAME = new QName("http://webservices.test.kick.com", "Account4kickInput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kick.test.webservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Account4KickInput }
     * 
     */
    public Account4KickInput createAccount4KickInput() {
        return new Account4KickInput();
    }

    /**
     * Create an instance of {@link PrefType }
     * 
     */
    public PrefType createPrefType() {
        return new PrefType();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Account }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.test.kick.com", name = "Account")
    public JAXBElement<Account> createAccount(Account value) {
        return new JAXBElement<Account>(_Account_QNAME, Account.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Account4KickInput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.test.kick.com", name = "Account4kickInput")
    public JAXBElement<Account4KickInput> createAccount4KickInput(Account4KickInput value) {
        return new JAXBElement<Account4KickInput>(_Account4KickInput_QNAME, Account4KickInput.class, null, value);
    }

}
