//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 03:29:01 PM EDT 
//


package org.example.testkickapp1service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.testkickapp1service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NoticeficationResponse_QNAME = new QName("http://www.example.org/TestKickapp1Service", "NoticeficationResponse");
    private final static QName _NotificationRequest_QNAME = new QName("http://www.example.org/TestKickapp1Service", "NotificationRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.testkickapp1service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotificationResponseType }
     * 
     */
    public NotificationResponseType createNotificationResponseType() {
        return new NotificationResponseType();
    }

    /**
     * Create an instance of {@link NotificationRequestType }
     * 
     */
    public NotificationRequestType createNotificationRequestType() {
        return new NotificationRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/TestKickapp1Service", name = "NoticeficationResponse")
    public JAXBElement<NotificationResponseType> createNoticeficationResponse(NotificationResponseType value) {
        return new JAXBElement<NotificationResponseType>(_NoticeficationResponse_QNAME, NotificationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/TestKickapp1Service", name = "NotificationRequest")
    public JAXBElement<NotificationRequestType> createNotificationRequest(NotificationRequestType value) {
        return new JAXBElement<NotificationRequestType>(_NotificationRequest_QNAME, NotificationRequestType.class, null, value);
    }

}
